name: Deploy to cPanel via SFTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v2

      - name: 🧱 Install dependencies and build
        run: |
          npm ci
          npm run build
          npm run export

      - name: 📤 Upload via SFTP using lftp
        uses: pressidium/lftp-mirror-action@v1.1.0
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          user: ${{ secrets.SFTP_USERNAME }}
          pass: ${{ secrets.SFTP_PASSWORD }}
          localDir: out
          remoteDir: public_html
          options: --verbose --parallel=2
