name: Deploy to cPanel via SFTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v2

      - name: 🧱 Install dependencies and build
        run: |
          npm ci
          npm run build
          npm run export

      - name: 📤 Upload via SFTP to cPanel
        uses: appleboy/sftp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          source: "out/*"
          target: "/home/${{ secrets.SFTP_USERNAME }}/public_html"
          strip_components: 1

